version: '3.3'

services:
  couch:
    container_name: vue-calculator-app-couch
    build: https://github.com/gribanov2la/docker-couchdb.git
    ports:
      - '3003:5984'
    environment:
      - COUCHDB_DBNAME=history
  sample-app:
    container_name: vue-calculator-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
    ports:
      - '8080:8080'
