version: '3.3'

services:
  couch:
    container_name: vue-calculator-app-couch
    build: https://github.com/gribanov2la/docker-couchdb.git
    ports:
      - '3003:5984'
    environment:
      - COUCHDB_DBNAME=mydb
  sample-app:
    container_name: vue-calculator-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
    ports:
      - '3002:8080'
    environment:
      - NODE_ENV=development
      - REACT_APP_DB_URL=http://localhost:3003/mydb
